# Generated by Django 4.0 on 2023-02-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songreccom', '0002_remove_quiz_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='op5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
