# Generated by Django 4.0 on 2023-04-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songreccom', '0006_alter_quiz_op1_alter_quiz_op2_alter_quiz_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mood', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
