# Generated by Django 4.0 on 2023-04-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songreccom', '0007_mood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mood',
            old_name='mood',
            new_name='mymood',
        ),
    ]
