# Generated by Django 4.0 on 2023-04-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songreccom', '0008_rename_mood_mood_mymood'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
